/**
 * Seed data for the offline / prototype mode.
 *
 * When Supabase env vars are not configured, the app falls back to the
 * in-memory mock client (see mockSupabase.ts) which is initialised from the
 * tables produced here. IDs for the primary demo accounts match the ones the
 * LoginScreen "Demo Mode" buttons dispatch (`demo-passenger`, `demo-driver`,
 * `demo-admin`) so both real login and demo login surface the same data.
 */

const NOW = Date.now();
const MIN = 60 * 1000;
const HOUR = 60 * MIN;
const DAY = 24 * HOUR;
const iso = (msAgo: number) => new Date(NOW - msAgo).toISOString();

// Boac, Marinduque area coordinates
const LOC = {
  market: { latitude: 13.4452, longitude: 121.8401, address: 'Boac Public Market' },
  college: { latitude: 13.4101, longitude: 121.8456, address: 'Marinduque State College, Tanza' },
  cathedral: { latitude: 13.4477, longitude: 121.8389, address: 'Boac Cathedral' },
  hospital: { latitude: 13.4419, longitude: 121.8442, address: 'Marinduque Provincial Hospital' },
  plaza: { latitude: 13.4463, longitude: 121.8408, address: 'Boac Plaza' },
  port: { latitude: 13.5247, longitude: 121.8665, address: 'Cawit Port' },
};

export const seedUsers = () => [
  {
    id: 'demo-passenger',
    auth_id: 'auth-passenger',
    user_type: 'passenger',
    email: 'passenger@demo.com',
    phone: '09171234567',
    name: 'Maria Santos',
    profile_photo_url: null,
    created_at: iso(120 * DAY),
    status: 'active',
    rating: 4.8,
    total_trips: 34,
  },
  {
    id: 'pas-2',
    auth_id: 'auth-pas-2',
    user_type: 'passenger',
    email: 'ana@mail.com',
    phone: '09181112222',
    name: 'Ana Reyes',
    profile_photo_url: null,
    created_at: iso(80 * DAY),
    status: 'active',
    rating: 4.6,
    total_trips: 12,
  },
  {
    id: 'pas-3',
    auth_id: 'auth-pas-3',
    user_type: 'passenger',
    email: 'jose@mail.com',
    phone: '09183334444',
    name: 'Jose Cruz',
    profile_photo_url: null,
    created_at: iso(60 * DAY),
    status: 'active',
    rating: 4.9,
    total_trips: 21,
  },
  {
    id: 'demo-driver',
    auth_id: 'auth-driver',
    user_type: 'driver',
    email: 'driver@demo.com',
    phone: '09195556666',
    name: 'Kuya Jojo',
    profile_photo_url: null,
    created_at: iso(200 * DAY),
    status: 'active',
    rating: 4.9,
    total_trips: 247,
    // driver-specific
    license_number: 'N03-12-345678',
    license_expiry: iso(-365 * DAY),
    verification_status: 'verified',
    vehicle_details: {
      plate_number: 'ABC-1234',
      make: 'Honda',
      model: 'TMX 155',
      year: 2021,
      color: 'Blue',
      capacity: 4,
    },
    toda_membership: 'FEDTODAB',
    bank_account: null,
    total_earnings: 84250,
    completed_trips: 247,
    current_status: 'online',
    last_location_update: iso(2 * MIN),
  },
  {
    id: 'drv-2',
    auth_id: 'auth-drv-2',
    user_type: 'driver',
    email: 'juan@toda.com',
    phone: '09197778888',
    name: 'Juan Dela Cruz',
    profile_photo_url: null,
    created_at: iso(150 * DAY),
    status: 'active',
    rating: 4.7,
    total_trips: 189,
    license_number: 'N03-98-765432',
    license_expiry: iso(-200 * DAY),
    verification_status: 'verified',
    vehicle_details: {
      plate_number: 'XYZ-5678',
      make: 'Yamaha',
      model: 'Sniper 155',
      year: 2020,
      color: 'Red',
      capacity: 4,
    },
    toda_membership: 'FEDTODAB',
    bank_account: null,
    total_earnings: 62100,
    completed_trips: 189,
    current_status: 'online',
    last_location_update: iso(5 * MIN),
  },
  {
    id: 'drv-3',
    auth_id: 'auth-drv-3',
    user_type: 'driver',
    email: 'pedro@toda.com',
    phone: '09199990000',
    name: 'Pedro Penduko',
    profile_photo_url: null,
    created_at: iso(30 * DAY),
    status: 'active',
    rating: 4.5,
    total_trips: 42,
    license_number: 'N03-11-223344',
    license_expiry: iso(-400 * DAY),
    verification_status: 'pending',
    vehicle_details: {
      plate_number: 'LMN-9012',
      make: 'Kawasaki',
      model: 'Barako',
      year: 2019,
      color: 'Black',
      capacity: 4,
    },
    toda_membership: 'FEDTODAB',
    bank_account: null,
    total_earnings: 15400,
    completed_trips: 42,
    current_status: 'offline',
    last_location_update: iso(3 * HOUR),
  },
  {
    id: 'demo-admin',
    auth_id: 'auth-admin',
    user_type: 'admin',
    email: 'admin@demo.com',
    phone: '09170000000',
    name: 'TODA Admin',
    profile_photo_url: null,
    created_at: iso(300 * DAY),
    status: 'active',
    rating: 5.0,
    total_trips: 0,
  },
];

const fare = (distance: number) => {
  const base = 15;
  const perKm = 8;
  return Math.round((base + distance * perKm) * 100) / 100;
};

const completedBooking = (
  id: string,
  passengerId: string,
  driverId: string,
  pickup: any,
  dropoff: any,
  distance: number,
  completedMsAgo: number
) => ({
  id,
  passenger_id: passengerId,
  driver_id: driverId,
  pickup_location: pickup,
  dropoff_location: dropoff,
  status: 'completed',
  scheduled_time: null,
  created_at: iso(completedMsAgo + 20 * MIN),
  accepted_at: iso(completedMsAgo + 18 * MIN),
  started_at: iso(completedMsAgo + 15 * MIN),
  completed_at: iso(completedMsAgo),
  distance,
  estimated_duration: Math.ceil((distance / 30) * 60),
  actual_duration: Math.ceil((distance / 28) * 60),
  base_fare: 15,
  per_km_rate: 8,
  total_fare: fare(distance),
  peak_hour_multiplier: 1,
  payment_method: 'cash',
  payment_status: 'completed',
  passenger_rating: null,
  driver_rating: null,
  notes: null,
});

export const seedBookings = () => [
  // Passenger history (demo-passenger)
  completedBooking('bk-1001', 'demo-passenger', 'demo-driver', LOC.market, LOC.college, 4.2, 2 * DAY),
  completedBooking('bk-1002', 'demo-passenger', 'drv-2', LOC.college, LOC.cathedral, 4.0, 5 * DAY),
  {
    ...completedBooking('bk-1003', 'demo-passenger', 'demo-driver', LOC.plaza, LOC.hospital, 1.1, 9 * DAY),
    status: 'cancelled',
    payment_status: 'pending',
    completed_at: null,
    started_at: null,
  },
  // Driver completed trips today (demo-driver) -> daily earnings
  completedBooking('bk-2001', 'pas-2', 'demo-driver', LOC.market, LOC.port, 9.4, 2 * HOUR),
  completedBooking('bk-2002', 'pas-3', 'demo-driver', LOC.cathedral, LOC.college, 3.8, 4 * HOUR),
  completedBooking('bk-2003', 'pas-2', 'demo-driver', LOC.hospital, LOC.market, 1.0, 6 * HOUR),
  // Pending requests for drivers to accept (driver flow)
  {
    id: 'bk-3001',
    passenger_id: 'pas-2',
    driver_id: null,
    pickup_location: LOC.plaza,
    dropoff_location: LOC.port,
    status: 'pending',
    scheduled_time: null,
    created_at: iso(3 * MIN),
    accepted_at: null,
    started_at: null,
    completed_at: null,
    distance: 9.8,
    estimated_duration: 20,
    actual_duration: null,
    base_fare: 15,
    per_km_rate: 8,
    total_fare: fare(9.8),
    peak_hour_multiplier: 1,
    payment_method: 'cash',
    payment_status: 'pending',
    passenger_rating: null,
    driver_rating: null,
    notes: null,
  },
  {
    id: 'bk-3002',
    passenger_id: 'pas-3',
    driver_id: null,
    pickup_location: LOC.college,
    dropoff_location: LOC.market,
    status: 'pending',
    scheduled_time: null,
    created_at: iso(1 * MIN),
    accepted_at: null,
    started_at: null,
    completed_at: null,
    distance: 4.2,
    estimated_duration: 9,
    actual_duration: null,
    base_fare: 15,
    per_km_rate: 8,
    total_fare: fare(4.2),
    peak_hour_multiplier: 1,
    payment_method: 'cash',
    payment_status: 'pending',
    passenger_rating: null,
    driver_rating: null,
    notes: null,
  },
];

export const seedFareMatrix = () => [
  {
    id: 'fare-1',
    base_fare: 15,
    per_km_rate: 8,
    peak_hour_multiplier: 1.5,
    peak_hours_enabled: true,
  },
];

export const seedActivityLogs = () => [
  {
    id: 'log-1',
    user_id: 'demo-driver',
    action_type: 'booking_completed',
    entity_type: 'booking',
    entity_id: 'bk-2001',
    description: 'Trip bk-2001 completed by Kuya Jojo (₱90.20)',
    metadata: {},
    severity: 'success',
    created_at: iso(2 * HOUR),
  },
  {
    id: 'log-2',
    user_id: 'pas-2',
    action_type: 'booking_created',
    entity_type: 'booking',
    entity_id: 'bk-3001',
    description: 'New booking request from Ana Reyes (Boac Plaza → Cawit Port)',
    metadata: {},
    severity: 'info',
    created_at: iso(3 * MIN),
  },
  {
    id: 'log-3',
    user_id: 'demo-admin',
    action_type: 'system_alert',
    entity_type: 'system',
    description: 'High demand detected in Boac Market area',
    metadata: {},
    severity: 'warning',
    created_at: iso(15 * MIN),
  },
  {
    id: 'log-4',
    user_id: 'drv-3',
    action_type: 'driver_status_changed',
    entity_type: 'driver',
    entity_id: 'drv-3',
    description: 'Driver Pedro Penduko went offline',
    metadata: {},
    severity: 'info',
    created_at: iso(3 * HOUR),
  },
  {
    id: 'log-5',
    user_id: 'demo-passenger',
    action_type: 'booking_cancelled',
    entity_type: 'booking',
    entity_id: 'bk-1003',
    description: 'Booking bk-1003 cancelled by passenger',
    metadata: {},
    severity: 'error',
    created_at: iso(9 * DAY),
  },
  {
    id: 'log-6',
    user_id: 'drv-2',
    action_type: 'user_action',
    entity_type: 'driver',
    entity_id: 'drv-2',
    description: 'Driver Juan Dela Cruz verification approved',
    metadata: {},
    severity: 'success',
    created_at: iso(1 * DAY),
  },
];

export const seedNotifications = () => [
  {
    id: 'ntf-1',
    user_id: 'demo-passenger',
    type: 'booking_update',
    title: 'Trip Completed',
    body: 'Your trip to Marinduque State College is complete. Salamat!',
    read: false,
    created_at: iso(2 * DAY),
  },
  {
    id: 'ntf-2',
    user_id: 'demo-driver',
    type: 'booking_request',
    title: 'New Booking Request',
    body: 'Pickup at Boac Plaza',
    booking_id: 'bk-3001',
    read: false,
    created_at: iso(3 * MIN),
  },
];

const docs = (uploaded: boolean) =>
  [
    'Barangay Clearance',
    'Community Tax Certificate (Cedula)',
    'OR/CR of Tricycle Unit',
    'Proof of Ownership',
    'TODA Membership Certificate',
  ].map((name) => ({ name, uploaded }));

export const seedFranchiseApplications = () => [
  {
    id: 'fr-1',
    driver_id: 'demo-driver',
    driver_name: 'Kuya Jojo',
    toda: 'FEDTODAB',
    plate_number: 'ABC-1234',
    type: 'new',
    status: 'issued',
    documents: docs(true),
    inspection_result: 'passed',
    payment_status: 'paid',
    fees: 1500,
    mtop_number: 'MTOP-2024-0147',
    remarks: 'Franchise active and in good standing.',
    created_at: iso(180 * DAY),
    updated_at: iso(150 * DAY),
  },
  {
    id: 'fr-2',
    driver_id: 'drv-2',
    driver_name: 'Juan Dela Cruz',
    toda: 'FEDTODAB',
    plate_number: 'XYZ-5678',
    type: 'new',
    status: 'document_verification',
    documents: docs(true),
    inspection_result: 'pending',
    payment_status: 'pending',
    fees: 1500,
    mtop_number: null,
    remarks: null,
    created_at: iso(4 * DAY),
    updated_at: iso(2 * DAY),
  },
  {
    id: 'fr-3',
    driver_id: 'drv-3',
    driver_name: 'Pedro Penduko',
    toda: 'FEDTODAB',
    plate_number: 'LMN-9012',
    type: 'renewal',
    status: 'inspection',
    documents: docs(true),
    inspection_result: 'pending',
    payment_status: 'pending',
    fees: 1000,
    mtop_number: null,
    remarks: 'Renewal of expired MTOP.',
    created_at: iso(6 * DAY),
    updated_at: iso(1 * DAY),
  },
];

export const seedDriverLocations = () => [
  { driver_id: 'demo-driver', latitude: 13.4452, longitude: 121.8401, timestamp: iso(2 * MIN) },
  { driver_id: 'drv-2', latitude: 13.4477, longitude: 121.8389, timestamp: iso(5 * MIN) },
];

/** Builds a fresh in-memory database snapshot. */
export const buildSeedDatabase = (): Record<string, any[]> => ({
  users: seedUsers(),
  bookings: seedBookings(),
  fare_matrix: seedFareMatrix(),
  activity_logs: seedActivityLogs(),
  notifications: seedNotifications(),
  driver_locations: seedDriverLocations(),
  franchise_applications: seedFranchiseApplications(),
});
